version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y jq  # Example: Installing jq

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 038462771019.dkr.ecr.eu-west-1.amazonaws.com
      - export REPO_URI=038462771019.dkr.ecr.eu-west-1.amazonaws.com/networkapp

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPO_URI:latest .
      - echo "Pushing image to ECR..."
      - docker push $REPO_URI:latest

  post_build:
    commands:
      - echo "Saving build artifacts..."
      - mkdir -p WebappPipeline/BuildArtif
      - echo "Build successful" > WebappPipeline/BuildArtif/build_info.txt

artifacts:
  files:
    - "WebappPipeline/BuildArtif/*"
